// words.js
const wordArray = [
    { word: "Pharaoh", hint: "The ruler of ancient Egypt, often considered a god-king." },
    { word: "Pyramid", hint: "A massive structure with a square base and triangular sides, built as tombs for pharaohs." },
    { word: "Hieroglyphics", hint: "A system of writing using pictorial symbols, used in ancient Egypt." },
    { word: "Nile", hint: "The longest river in the world, flowing through Egypt and providing water and fertile land." },
    { word: "Mummy", hint: "A preserved body, wrapped in cloth, typically for a deceased person." },
    { word: "Sphinx", hint: "A mythical creature with the body of a lion and the head of a pharaoh." },
    { word: "Papyrus", hint: "A type of paper made from reeds, used for writing in ancient Egypt." },
    { word: "Obelisk", hint: "A tall, four-sided stone monument with a pointed top, often used as a symbol of power." },
    { word: "Ankh", hint: "A hieroglyphic symbol representing life and immortality." },
    { word: "Sarcophagus", hint: "A stone coffin used for burying the dead in ancient Egypt." },
    { word: "Scarab", hint: "A type of beetle associated with rebirth and protection in ancient Egyptian culture." },
    { word: "Deity", hint: "A god or goddess, often worshiped in ancient Egyptian religion." },
    { word: "Rosetta Stone", hint: "A stone slab inscribed with three scripts, crucial in deciphering hieroglyphs." },
    { word: "Cartouche", hint: "An oval shape enclosing hieroglyphs to represent a name or title." },
    { word: "Amulet", hint: "A small charm believed to bring protection or good fortune." },
    { word: "Ka", hint: "In Egyptian belief, the spiritual essence or soul of a person." },
    { word: "Ozymandias", hint: "The Greek name for the Egyptian pharaoh Ramses II, made famous by a poem." },
    { word: "Valley of the Kings", hint: "A burial site for pharaohs and nobles in ancient Egypt." },
    { word: "Canopic Jars", hint: "Containers used to store the organs of the deceased during mummification." },
    { word: "Shaduf", hint: "A device used for irrigation, raising water from the Nile onto fields." },
    { word: "Hapi", hint: "The god of the Nile, associated with fertility and abundance." },
    { word: "Crook and Flail", hint: "Symbols of pharaonic power and kingship." },
    { word: "Nubia", hint: "An ancient region located to the south of Egypt, known for its rich history." },
    { word: "Book of the Dead", hint: "A collection of spells and texts to guide the deceased through the afterlife." },
    { word: "Thebes", hint: "An ancient Egyptian city and capital during different periods." },
    { word: "Bastet", hint: "The goddess of home, fertility, and domesticity, often depicted as a lioness or with a cat's head." },
    { word: "Horus", hint: "The god of the sky, often depicted with the head of a falcon." },
    { word: "Ma'at", hint: "The concept of balance, truth, and justice in ancient Egyptian culture." },
    { word: "Obelisk", hint: "A tall, four-sided stone monument with a pointed top, often used as a symbol of power." },
    { word: "Pyramidion", hint: "The capstone of an Egyptian pyramid, often made of gold or a precious material." },
    { word: "Hyksos", hint: "A group of foreigners who ruled part of Egypt during the Second Intermediate Period." },
    { word: "Thoth", hint: "The god of wisdom, writing, and knowledge, often depicted with the head of an ibis." },
    { word: "Nefertiti", hint: "An Egyptian queen known for her beauty, wife of Pharaoh Akhenaten." },
    { word: "Akhet", hint: "The Egyptian word for the horizon, where the sun rose and set." },
    { word: "Amarna Period", hint: "A time in Egyptian history associated with Pharaoh Akhenaten's religious reforms." },
    { word: "Nile Delta", hint: "The fertile region where the Nile River splits into multiple branches before emptying into the Mediterranean Sea." },
    { word: "Hyroglossia", hint: "The study of ancient Egyptian hieroglyphs and their decipherment." },
    { word: "Lotus", hint: "A flower symbolizing rebirth and regeneration in ancient Egypt." },
    { word: "The Great Sphinx of Giza", hint: "A massive statue with the body of a lion and the head of a pharaoh, guarding the pyramids." },
    { word: "Rosetta Stone", hint: "A crucial artifact that helped scholars decipher ancient Egyptian hieroglyphs." },
    { word: "Pyramid Complex", hint: "The area surrounding a pyramid, often including temples and other structures." },
    { word: "Memphis", hint: "An ancient city in Lower Egypt, an important center of culture and trade." },
    { word: "Ra", hint: "The sun god, a major deity in Egyptian mythology." },
    { word: "Nemes", hint: "A striped headdress worn by pharaohs, often seen in depictions." },
    { word: "Luxor", hint: "A city in modern-day Egypt, known for its historical sites and temples." },
    { word: "Valley of the Queens", hint: "A burial site for queens and princesses in ancient Egypt." },
    { word: "Scarab Bracelet", hint: "Jewelry featuring a scarab beetle design, thought to bring good luck." },
    { word: "Anubis", hint: "The god of mummification and the afterlife, often depicted with the head of a jackal." },
    { word: "Heliopolis", hint: "An ancient city associated with the worship of the sun god Ra." },
    { word: "Osiris", hint: "The god of the afterlife and the dead, associated with rebirth and regeneration." }
];

export default wordArray;
