// words.js
const wordArray = [
    { word: "Pharaoh", hint: "A title used in ancient Egypt to refer to the rulers of the country." },
    { word: "Hieroglyphics", hint: "A system of writing in which pictures (glyphs) represent words or sounds." },
    { word: "Pyramid", hint: "A monumental structure with a square or triangular base and sloping sides that meet in a point at the top, typically used as a tomb for Pharaohs." },
    { word: "Sarcophagus", hint: "A stone coffin, typically adorned with hieroglyphics and used for holding mummies." },
    { word: "Mummy", hint: "A preserved body, typically wrapped in cloth, created through a process called mummification." },
    { word: "Nile River", hint: "The longest river in the world, flowing through Egypt and playing a vital role in its history and agriculture." },
    { word: "Ankh", hint: "An ancient Egyptian symbol representing life and immortality, often depicted as a cross with a loop at the top." },
    { word: "Obelisk", hint: "A tall, narrow, four-sided monument with a pointed top, often made of a single piece of stone." },
    { word: "Scarab", hint: "A type of dung beetle that was revered by the ancient Egyptians as a symbol of transformation and protection." },
    { word: "Sphinx", hint: "A mythical creature with the body of a lion and the head of a human or another animal, often seen in Egyptian art and architecture." },
    { word: "Horus", hint: "An ancient Egyptian god of the sky, often depicted as a falcon or with a falcon head." },
    { word: "Cleopatra", hint: "The last pharaoh of ancient Egypt, known for her beauty and her relationships with Julius Caesar and Mark Antony." },
    { word: "Akhenaten", hint: "An Egyptian pharaoh known for his attempt to replace the traditional Egyptian pantheon with the worship of the sun god Aten." },
    { word: "Thebes", hint: "An ancient Egyptian city located along the Nile River and known for its temples and monuments." },
    { word: "Hathor", hint: "An ancient Egyptian goddess associated with music, dance, and motherhood." },
    { word: "Papyrus", hint: "A type of paper made from the pith of the papyrus plant, widely used for writing in ancient Egypt." },
    { word: "Canopic Jars", hint: "Containers used in the mummification process to hold and protect the internal organs of the deceased." },
    { word: "Amon-Ra", hint: "An ancient Egyptian god often considered the king of the gods and associated with the sun." },
    { word: "Cartouche", hint: "An oval or oblong figure in ancient Egyptian hieroglyphics containing the name of a ruler or deity." },
    { word: "Hapi", hint: "An ancient Egyptian god of the Nile and fertility, often depicted as a man with large breasts and a blue or green complexion." },
    { word: "Sekhmet", hint: "An ancient Egyptian goddess with a lioness head, associated with war and healing." },
    { word: "Book of the Dead", hint: "A collection of spells and prayers that were buried with the deceased to guide them safely through the afterlife." },
    { word: "Hyksos", hint: "A group of foreign rulers who briefly controlled parts of Egypt during the Second Intermediate Period." },
    { word: "Nefertiti", hint: "An Egyptian queen known for her beauty and her role in the religious changes initiated by her husband Akhenaten." },
    { word: "Rosetta Stone", hint: "A stone inscribed with the same text in three scripts, including hieroglyphics, which helped scholars decipher ancient Egyptian writing." },
    { word: "Nubia", hint: "A region to the south of Egypt, known for its interactions and conflicts with the Egyptian civilization." },
    { word: "Abydos", hint: "An ancient Egyptian city and burial site, considered a sacred place associated with Osiris, the god of the afterlife." },
    //check 
    { word: "Ma'at", hint: "The ancient Egyptian concept of truth, balance, and order, often personified as a goddess." },
    //
    { word: "Cobra", hint: "A venomous snake often associated with protection and the Egyptian goddess Wadjet." },
    { word: "Scarab Beetle", hint: "A type of beetle revered in ancient Egypt as a symbol of rebirth and transformation." },
    { word: "Karnak Temple", hint: "A vast temple complex in Luxor, Egypt, dedicated to the god Amun-Ra and known for its impressive columns and statues." },
    { word: "Sobek", hint: "An ancient Egyptian god associated with the Nile and crocodiles, often depicted with a crocodile head." },
    { word: "Valley of the Kings", hint: "A royal burial site in Egypt's Luxor region, known for its tombs and chambers, including that of Tutankhamun." },
    { word: "Ra", hint: "An ancient Egyptian sun god, often depicted with a sun disk on his head." },
    { word: "Nefertari", hint: "An Egyptian queen known for her elaborate tomb in the Valley of the Queens." },
    { word: "Nemes", hint: "A striped headcloth worn by pharaohs in ancient Egypt, often seen in statues and paintings." },
    { word: "Bastet", hint: "An ancient Egyptian goddess with the head of a lioness or domestic cat, associated with home and fertility." },
    { word: "Amarna Period", hint: "A time during the 18th dynasty when Akhenaten moved the capital to Akhetaten (modern Amarna) and introduced religious reforms." },
    { word: "Horus Eye", hint: "Also known as the Eye of Horus, it is a symbol of protection and healing in ancient Egyptian mythology." },
    { word: "Imhotep", hint: "An ancient Egyptian polymath known for his contributions to medicine, architecture, and as the architect of the Step Pyramid." },
    { word: "Scarab Amulet", hint: "A small amulet in the shape of a scarab beetle, often worn as a symbol of protection and rebirth." },
    { word: "Lotus Flower", hint: "A symbol of rebirth in ancient Egypt, often associated with the sun and creation myths." },
    { word: "Ptah", hint: "An ancient Egyptian creator god and patron of craftsmen, often depicted as a man holding a staff." },
    { word: "Anubis", hint: "An ancient Egyptian god associated with mummification and the afterlife, often depicted as a jackal-headed figure." },
    { word: "Nekhbet", hint: "An ancient Egyptian vulture goddess associated with childbirth and maternity." },
    { word: "Senet", hint: "An ancient Egyptian board game, one of the world's oldest known board games." },
    { word: "Sistrum", hint: "A musical instrument used in ancient Egyptian religious ceremonies, often associated with the goddess Hathor." },
    { word: "Shaduf", hint: "An ancient Egyptian irrigation tool used for lifting water from the Nile River." },
    { word: "Benben Stone", hint: "A sacred stone in Egyptian mythology, often associated with creation and the primordial mound." }
];

export default wordArray;
