// words.js
const wordArray = [
    { word: "grape", hint: "A small fruit often found in clusters" },
    { word: "watermelon", hint: "A large fruit with a green rind and red flesh" },
    { word: "canary", hint: "noun. any of several Old World finches of the genus Serinus, especially S. canaria(common canary ), native to the Canary Islands and often kept as a pet, in the wild being greenish with brown streaks above and yellow below and in domesticated varieties usually bright yellow or pale yellow." },
    { word: "postgraduate", hint: "adjective. of, pertaining to, characteristic of, or consisting of post-graduates" },
    { word: "anadromous", hint: "adjective. (of fish) migrating from salt water to spawn in fresh water, as salmon of the genera Salmo and Oncorhynchus (distinguished from catadromous)." },
    { word: "heehaw", hint: "noun. the braying sound made by a donkey." },
    { word: "subsolar", hint: "adjective. situated beneath the sun or between the earth and the sun." },
    { word: "scenography", hint: "noun. the art of representing objects in accordance with the rules of perspective." },
    { word: "clinch", hint: "verb (used with object). to settle (a matter) decisively" },
    { word: "sortie", hint: "noun. a rapid movement of troops from a besieged place to attack the besiegers." },
    { word: "nursemaid", hint: "noun. a woman or girl employed to care for a child or several children, especially in a household." },
    { word: "inceptive", hint: "adjective. beginning" },
    { word: "consecrate", hint: "verb (used with object). to make or declare sacred" },
    { word: "apterygial", hint: "adjective. having no wings, fins, or limbs, as snakes and eels." },
    { word: "encyclopedism", hint: "noun. encyclopedic learning." },
    { word: "insignia", hint: "noun. a badge or distinguishing mark of office or honor" },
    { word: "lobar", hint: "adjective. of or relating to a lobe, as of the lungs." },
    { word: "tonguing", hint: "noun. the manipulation of the tongue in playing a wind instrument to interrupt the tone and produce a staccato effect." },
    { word: "ferroelectric", hint: "adjective. pertaining to a substance that possesses spontaneous electric polarization such that the polarization can be reversed by an electric field." },
    { word: "mariculture", hint: "noun. marine aquaculture." },
    { word: "chatty", hint: "adjective. characterized by friendly and informal talk or writing, often about minor or personal matters" },
    { word: "deify", hint: "verb (used with object). to make a god of" },
    { word: "optical", hint: "adjective. of, relating to, or applying optics or the principles of optics." },
    { word: "trickery", hint: "noun. the use or practice of tricks or stratagems to deceive" },
    { word: "culture", hint: "noun. the quality in a person or society that arises from a concern for what is regarded as excellent in arts, letters, manners, scholarly pursuits, etc." },
    { word: "limit", hint: "noun. the final, utmost, or furthest boundary or point as to extent, amount, continuance, procedure, etc." },
    { word: "enrichment", hint: "noun. an act of enriching." },
    { word: "radio", hint: "noun. wireless telegraphy or telephony" },
    { word: "misadvise", hint: "verb (used with object). to give bad or inappropriate advice to." },
    { word: "derivation", hint: "noun. the act or fact of deriving or of being derived." },
    { word: "medievalism", hint: "noun. the spirit, practices, or methods of the Middle Ages." },
    { word: "gravitate", hint: "verb (used without object). to move or tend to move under the influence of gravitational force." },
    { word: "carillon", hint: "noun. a set of stationary bells hung in a tower and sounded by manual or pedal action, or by machinery." },
    { word: "drew", hint: "verb. simple past tense of draw." },
    { word: "opposite", hint: "adjective. situated, placed, or lying face to face with something else or each other, or in corresponding positions with relation to an intervening line, space, or thing" },
    { word: "shuck", hint: "noun. a husk or pod, as the outer covering of corn, hickory nuts, chestnuts, etc." },
    { word: "eradicate", hint: "verb (used with object). to remove or destroy utterly" },
    { word: "legging", hint: "noun. a covering for the leg, usually extending from the ankle to the knee but sometimes higher, worn by soldiers, riders, workers, etc." },
    { word: "belong", hint: "verb (used without object). to be in the relation of a member, adherent, inhabitant, etc. (usually followed by to)" },
    { word: "turbofan", hint: "noun. a jet engine having a large impeller that takes in air, part of which is used in combustion of fuel, the remainder being mixed with the products of combustion to form a low-velocity exhaust jet." },
    { word: "frost", hint: "noun. a degree or state of coldness sufficient to cause the freezing of water." },
    { word: "metaphase", hint: "noun. the stage in mitosis or meiosis in which the duplicated chromosomes line up along the equatorial plate of the spindle." },
    { word: "yad", hint: "noun. a tapered, usually ornamented rod, usually of silver, with the tip of the tapered part forming a fist with the index finger extended, used by the reader of a scroll of the Torah as a place marker." },
    { word: "trademark", hint: "noun. any name, symbol, figure, letter, word, or mark adopted and used by a manufacturer or merchant in order to designate specific goods and to distinguish them from those manufactured or sold by others. A trademark is proprietary and is usually registered with the Patent and Trademark Office to assure its exclusive use by its owner or licensee." },
    { word: "strangeness", hint: "noun. the quality or condition of being strange." },
    { word: "equinoctial", hint: "adjective. pertaining to an equinox or the equinoxes, or to the equality of day and night." },
    { word: "buckskin", hint: "noun. the skin of a buck or deer." },
    { word: "mastoid", hint: "adjective. of or relating to the mastoid process." },
    { word: "priestess", hint: "noun. a woman who officiates in sacred rites." },
    { word: "new", hint: "adjective. of recent origin, production, purchase, etc." },
    { word: "ohmage", hint: "noun. electric resistance expressed in ohms." },
    { word: "monothematic", hint: "adjective. having a single theme." },
    { word: "cordless", hint: "adjective. lacking a cord." },
    { word: "disembark", hint: "verb (used without object). to go ashore from a ship." },
    { word: "sigmoid", hint: "adjective. shaped like the letter C." },
    { word: "tartarous", hint: "adjective. consisting of or containing tartar." },
    { word: "keynote", hint: "noun. the note or tone on which a key or system of tones is founded" },
    { word: "amoretto", hint: "noun. a little cupid." },
    { word: "pasty", hint: "adjective. of or like paste in consistency, texture, color, etc." },
    { word: "charwoman", hint: "noun. a woman hired to do general cleaning, especially in an office or large house." },
    { word: "verisimilitude", hint: "noun. the appearance or semblance of truth" },
    { word: "mandible", hint: "noun. the bone of the lower jaw." },
    { word: "incurvate", hint: "adjective. curved, especially inward." },
    { word: "foretaste", hint: "noun. a slight and partial experience, knowledge, or taste of something to come in the future" },
    { word: "admonitory", hint: "adjective. tending or serving to admonish" },
    { word: "backstroke", hint: "noun. a backhanded stroke." },
    { word: "excavation", hint: "noun. a hole or cavity made by excavating." },
    { word: "retire", hint: "verb (used without object). to withdraw from one's career, occupation, or office, usually because of age" },
    { word: "disquiet", hint: "noun. lack of calm, peace, or ease" },
    { word: "quick", hint: "adjective. done, proceeding, or occurring with promptness or rapidity, as an action, process, etc." },
    { word: "clofibrate", hint: "noun. a substance, C12H15ClO3, used principally to reduce elevated plasma triglyceride and cholesterol levels." },
    { word: "schmear", hint: "noun. a dab, as of cream cheese, spread on a roll, bagel, or the like." },
    { word: "stanchion", hint: "noun. an upright bar, beam, post, or support, as in a window, stall, ship, etc." },
    { word: "subcaliber", hint: "adjective. noting or pertaining to ammunition of smaller caliber than the gun in which it is used." },
    { word: "plaice", hint: "noun. a European flatfish, Pleuronectes platessa, used for food." },
    { word: "tryout", hint: "noun. a trial or test to ascertain fitness for some purpose." },
    { word: "grime", hint: "noun. dirt, soot, or other filthy matter, especially adhering to or embedded in a surface." },
    { word: "shawm", hint: "noun. an early musical woodwind instrument with a double reed" },
    { word: "xenia", hint: "noun. the influence or effect of pollen on a structure other than the embryo, as the seed or fruit." },
    { word: "federal", hint: "adjective. pertaining to or of the nature of a union of states under a central government distinct from the individual governments of the separate states, as in federal government" },
    { word: "shakedown", hint: "noun. extortion, as by blackmail or threats of violence." },
    { word: "choleric", hint: "adjective. extremely irritable or easily angered" },
    { word: "untried", hint: "adjective. not tried" },
    { word: "landlord", hint: "noun. a person or organization that owns and leases apartments to others." },
    { word: "cuff", hint: "noun. a fold or band serving as a trimming or finish for the bottom of a sleeve." },
    { word: "expletive", hint: "noun. an interjectory word or expression, frequently profane" },
    { word: "mediumistic", hint: "adjective. pertaining to a spiritualistic medium." },
    { word: "biryani", hint: "noun. a spicy Indian dish of rice with meat or vegetables, flavored with saffron or turmeric." },
    { word: "course", hint: "noun. a direction or route taken or to be taken." },
    { word: "flange", hint: "noun. a projecting rim, collar, or ring on a shaft, pipe, machine housing, etc., cast or formed to give additional strength, stiffness, or supporting area, or to provide a place for the attachment of other objects." }
];

export default wordArray;
